### ISSUE TITLE
Casi d'uso

### ISSUE THREAD

**Issue by giodabg** [whMino/Norberto#2]

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/9990935/Casi.d.uso.docx)

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/9994567/Casi.d.uso.docx)
Casi d'uso 12/11/22

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/10023062/Casi.d.uso.docx)
Casi d'uso 14/11/22

**Comment by giodabg** [comment]
Mancano i seguenti casi d'uso:
- aggiungi catalogo
- visualizzazione catalogo
- visualizzazione notizie
- visualizzazione novità

Osservazioni sui casi d'uso:
- nella registrazione manca il flusso in cui i dati siano errati (formato errato o username duplicato)
- nel login manca il flusso username e password non corrispondenti
- nel caso d'uso con le preferenze manca la visualizzazione delle preferenze e della località già inserita. Si separa il caso d'uso sulla modifica delle preferenze e del luogo, quando normalmente la modifica del profilo utente si fa tutta assieme con un solo bottone salva. Manca il flusso relativo al fatto che si cancella una preferenza inesistente o quello sul luogo errato. C'è un massimo alle preferenze che si possono aggiungere?
- nel caso visualizzazione giornali, non si capisce come ci si arriva, come vengono scelti i giornali popolari e come si usano le preferenze. Perchè come flusso alternativo si passa alle impostazioni e non alla home page?
- nel caso Visualizzazione giornale completo, non si capisce quali dati mostra il sistema ossia in che cosa consiste il giornale completo

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/10041684/Casi.d.uso.docx)
18/11/22

**Comment by giodabg** [comment]
Il documento deve fare riferimento al prodotto finale comprensivo di TUTTE le funzionalità.

Ricordo che il documento dei casi d'uso deve essere consistente con il documento che descrive la GUI e il documento che descrive i dati.

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/10046427/Casi.d.uso.docx)
19/11/22

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/10047210/Casi.d.uso.docx)
19/11/22

**Comment by Bubuz123** [comment]
Casi d'uso finali:
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/10094533/Casi.d.uso.docx)
