### ISSUE TITLE
Analisi dei dati

### ISSUE THREAD

**Issue by giodabg** [whMino/Norberto#3]

**Comment by Bubuz123** [comment]
[Casi d'uso.docx](https://github.com/whMino/Norberto/files/9982088/Casi.d.uso.docx)

**Comment by Bubuz123** [comment]
![Analisi dei dati](https://user-images.githubusercontent.com/100220132/201463301-95a09b77-a757-48d9-9657-26b5645e3d81.png)
Documentazione parziale aggiunta nel progetto da D'alessandro.

**Comment by giodabg** [comment]
L'analisi dei dati non è composta semplicemente dal diagramma, ma prevede la spiegazione di che cosa contengo.
Il nome delle classi non può essere un verbo o una pagina web. 
In uno schema dati non devono comparire "Schermata home" e "Visualizza giornali" ma solo "Giornale: nome e percorso" e "Utente: ...."

Lo schema delle pagine del sito web fa parte dell'interfaccia GUI e non nella parte dati.

**Comment by giodabg** [comment]
La documentazione dei dati dovrebbe essere un documento contenere oltre al diagramma con le classi e i loro attributi:
- la descrizione di ogni attributo in termini di contenuto, tipo del dato e di obbligatorietà/opzionalità
- la descrizione dei legami tra le varie classi/attributi

Il solo diagramma non è sufficiente.

A questo aggiungo che la documentazione deve fare riferimento al prodotto finale comprensivo di TUTTE le funzionalità.

Ricordo che il documento con i dati deve essere consistente con il documento che descrive i casi d'uso e il documento che descrive la GUI.

**Comment by Bubuz123** [comment]
[Analisi dei dati.docx](https://github.com/whMino/Norberto/files/10046506/Analisi.dei.dati.docx)
![Diagramma](https://user-images.githubusercontent.com/100220132/202842557-c90141ec-9da1-4e7e-a2fa-66bdb9d327d4.png)
19/11/22

**Comment by Bubuz123** [comment]
Analisi dei dati finali:
[Analisi dei dati.docx](https://github.com/whMino/Norberto/files/10094542/Analisi.dei.dati.docx)
![Diagramma](https://user-images.githubusercontent.com/100220132/204035757-f140fb94-abe1-495e-9f13-02f8547a2256.png)
