### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by giodabg** [whMino/Norberto#4]

**Comment by giodabg** [comment]
disegno dell'interfaccia grafica (immagini)

Le immagini dovrebbero essere in due versioni: bozza anche in forma di schizzo a mano libera, versione di rilascio con una grafica identica o vicina alla versione finale

**Comment by Bubuz123** [comment]
![sfondo schermata principale](https://user-images.githubusercontent.com/100220132/201362347-195fcc2d-80ee-4809-beae-7f367ec13fa8.jpg)
![schermata login](https://user-images.githubusercontent.com/100220132/201362361-7054faba-9b2c-4726-838c-7ae106270824.png)

**Comment by Bubuz123** [comment]
![Home_jourubuz](https://user-images.githubusercontent.com/100220132/201462769-d46f3f18-7cb6-481a-9dee-7973de948b7e.png)

**Comment by giodabg** [comment]
Il sito è composto da pagine che contengono informazioni non memorizzate nei dati:
- notizie sportive, attualità politica, notizie dal mondo
- nell'archivio sono presenti dei cataloghi di non si sa che cosa e la funzione aggiungi
- non è prevista da nessuna parte la funzione di ricerca
- manca un'immagine del menù
- la grafica delle varie pagine non è consistente (sembrano 3 siti differenti)

**Comment by giodabg** [comment]
Il documento deve descrivere l'interfaccia del prodotto finale comprensivo di tutte le funzionalità (immagini con spiegazione/didascalia).

Un insieme di immagini caricate in una cartella, va bene solo come bozza, ma la versione finale deve essere un documento unico che permetta di capire il legame tra GUI, casi d'uso e dati.

Ricordo che il documento con la GUI deve essere consistente con il documento che descrive i casi d'uso e il documento che descrive i dati.

**Comment by Bubuz123** [comment]
Grafica finale:
Catalogo:
![Catalogo](https://user-images.githubusercontent.com/100220132/204034861-2af11b0c-9ac2-44a7-b5f5-ebf736324242.PNG)
Giornale:
![Giornale](https://user-images.githubusercontent.com/100220132/204034867-d9421388-c94b-4652-8ce3-e419679529c9.PNG)
Home:
![Home](https://user-images.githubusercontent.com/100220132/204034868-33061794-5b26-4e8e-9b3a-441d1fe5e053.PNG)
Impostazioni:
![Impostazioni](https://user-images.githubusercontent.com/100220132/204034870-a050f95b-b196-4a2c-8934-d57f58250002.PNG)
Login:
![Login](https://user-images.githubusercontent.com/100220132/204034879-05e55d89-9cd4-4574-9149-0eeee9549412.PNG)
