### ISSUE TITLE
Aggiornamento WBS

### ISSUE THREAD

**Issue by giodabg** [whMino/Norberto#5]

**Comment by Bubuz123** [comment]
WBS 05/11/22
[Tempi progetto.zip](https://github.com/whMino/Norberto/files/9943979/Tempi.progetto.zip)

**Comment by Bubuz123** [comment]
WBS 12/11/22
[Tempi progetto.zip](https://github.com/whMino/Norberto/files/9994495/Tempi.progetto.zip)
